import 'package:drop_down_list/model/selected_list_item.dart';
import 'package:get/get.dart';

final List<SelectedListItem> itemscolorsList = [
  SelectedListItem(data: "278".tr, value: "Red"),
  SelectedListItem(data: "279".tr, value: "Green"),
  SelectedListItem(data: "280".tr, value: "Blue"),
  SelectedListItem(data: "281".tr, value: "Yellow"),
  SelectedListItem(data: "282".tr, value: "Black"),
  SelectedListItem(data: "283".tr, value: "White"),
  SelectedListItem(data: "284".tr, value: "Orange"),
  SelectedListItem(data: "285".tr, value: "Purple"),
  SelectedListItem(data: "286".tr, value: "Pink"),
  SelectedListItem(data: "287".tr, value: "Brown"),
  SelectedListItem(data: "288".tr, value: "Gray"),
  SelectedListItem(data: "289".tr, value: "Cyan"),
  SelectedListItem(data: "290".tr, value: "Magenta"),
  SelectedListItem(data: "291".tr, value: "Lime"),
  SelectedListItem(data: "292".tr, value: "Maroon"),
  SelectedListItem(data: "293".tr, value: "Navy"),
  SelectedListItem(data: "294".tr, value: "Olive"),
  SelectedListItem(data: "295".tr, value: "Teal"),
  SelectedListItem(data: "296".tr, value: "Silver"),
  SelectedListItem(data: "297".tr, value: "Gold"),
  SelectedListItem(data: "298".tr, value: "Beige"),
  SelectedListItem(data: "299".tr, value: "Coral"),
  SelectedListItem(data: "300".tr, value: "Turquoise"),
  SelectedListItem(data: "301".tr, value: "Violet"),
  SelectedListItem(data: "302".tr, value: "Indigo"),
  SelectedListItem(data: "303".tr, value: "Lavender"),
  SelectedListItem(data: "304".tr, value: "Mint"),
  SelectedListItem(data: "305".tr, value: "Chocolate"),
  SelectedListItem(data: "306".tr, value: "Crimson"),
  SelectedListItem(data: "307".tr, value: "Khaki"),
  SelectedListItem(data: "308".tr, value: "Salmon"),
  SelectedListItem(data: "309".tr, value: "Plum"),
];
